/**
 * PDF generation for outbound freight Quote Requests
 * (a one-page document to send to a forwarder/shipping agent asking for a rate)
 */
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

const NAVY = [14, 37, 68];
const MUTED = [107, 114, 128];
const ROW_ALT = [248, 250, 252];

const TRANSPORT_LABELS = { sea: 'Sea Freight', air: 'Air Freight', road: 'Road Freight' };

const fmt = (v, suffix = '') => (v === null || v === undefined || v === '' ? '—' : `${v}${suffix}`);
const fmtDate = (d) => {
  if (!d) return '—';
  const parsed = new Date(d);
  return isNaN(parsed.getTime()) ? String(d) : parsed.toLocaleDateString('en-ZA', { year: 'numeric', month: 'short', day: '2-digit' });
};

export function generateQuoteRequestPDF(req) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const reference = `QR-${String(req.id).padStart(5, '0')}`;

  // Header band
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageWidth, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont(undefined, 'bold');
  doc.text('Freight Quote Request', 14, 17);
  doc.setFontSize(9);
  doc.setFont(undefined, 'normal');
  doc.text('Synercore Import Schedule', pageWidth - 14, 12, { align: 'right' });
  doc.text(`Ref: ${reference}`, pageWidth - 14, 18, { align: 'right' });
  doc.text(`Date: ${fmtDate(req.created_at || new Date())}`, pageWidth - 14, 24, { align: 'right' });

  let y = 38;
  doc.setTextColor(...NAVY);
  doc.setFontSize(11);
  doc.setFont(undefined, 'bold');
  doc.text('To', 14, y);
  doc.setFont(undefined, 'normal');
  doc.setFontSize(10);
  doc.text(req.forwarder_name || '—', 30, y);
  if (req.forwarder_email) {
    doc.setTextColor(...MUTED);
    doc.setFontSize(9);
    doc.text(req.forwarder_email, 30, y + 5);
    doc.setTextColor(...NAVY);
  }

  y += 14;
  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.text(
    'We would like to request your best rate and estimated transit time for the shipment detailed below.',
    14, y
  );

  y += 8;
  autoTable(doc, {
    startY: y,
    head: [['Shipment Details', '']],
    body: [
      ['Mode', TRANSPORT_LABELS[req.transport_mode] || fmt(req.transport_mode)],
      ['Incoterm', fmt(req.incoterm)],
      ['Origin', fmt(req.origin)],
      ...(req.collection_address ? [['Collection Address', req.collection_address]] : []),
      ['Destination', fmt(req.destination)],
      ['Cargo Ready Date', fmtDate(req.cargo_ready_date)],
      ['Required Delivery Date', fmtDate(req.required_date)],
    ],
    theme: 'plain',
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: ROW_ALT },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 55 } },
  });

  y = doc.lastAutoTable.finalY + 8;
  autoTable(doc, {
    startY: y,
    head: [['Cargo Details', '']],
    body: [
      ['Supplier', fmt(req.supplier_name)],
      ['Description', fmt(req.cargo_description)],
      ['HS Code', fmt(req.hs_code)],
      ['Gross Weight', fmt(req.gross_weight_kg, ' kg')],
      ['Volume', fmt(req.volume_cbm, ' CBM')],
      ['Pallets / Packages', fmt(req.pallet_count)],
    ],
    theme: 'plain',
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: NAVY, textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: ROW_ALT },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 55 } },
  });

  y = doc.lastAutoTable.finalY + 8;

  if (req.notes) {
    doc.setFont(undefined, 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...NAVY);
    doc.text('Notes', 14, y);
    y += 5;
    doc.setFont(undefined, 'normal');
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    const lines = doc.splitTextToSize(req.notes, pageWidth - 28);
    doc.text(lines, 14, y);
    y += lines.length * 4.5 + 6;
  }

  y += 4;
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  doc.text('Please reply with your rate, transit time, and validity period at your earliest convenience.', 14, y);
  y += 10;
  doc.setFont(undefined, 'bold');
  doc.text(`Requested by: ${req.requested_by_username || '—'}`, 14, y);

  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(...MUTED);
  doc.text('Generated by Synercore Import Schedule', 14, pageHeight - 9);

  doc.save(`quote-request-${reference}.pdf`);
}
